const journalData= [
  {
    title: "Cloud-based database framework of corrosion detecting and grading for temporary steel pipe supports",
    main_author: "Ali Akbar",
    co_authors: "Goeun Choi, James Mugo Njoroge, Soonwook Kwon",
    journal: "Journal of Asian Architecture and Building Engineering",
    year: "2025",
    doi: "doi.org/10.1080/13467581.2025.2520468",
    abstract: "Failures of temporary steel pipe supports due to corrosion present significant safety risks and economic challenges within the construction industry, stemming from the absence of robust logging and quality inspection systems. This paper introduces a novel cloud-based database framework designed for the automated detection and grading of these critical components, aiming to enhance site safety and equipment management. The proposed multi-detection system utilizes state-of-the-art deep learning architectures, including YOLOv9 for object detection and YOLOv9-seg for instance segmentation. On held-out test sets, the system demonstrated robust performance, achieving a mean average precision (mAP@[.5:.95]) of 0.71 for the precise detection of steel pipe supports. These analytical capabilities are integrated into a unified web server, which combines web development technologies with equipment analysis results. This platform facilitates real-time data visualization and employs a novel, practical checklist-based grading system to systematically assess equipment condition according to industry standards and site-specific repairability. The primary contribution is a comprehensive online management system that provides a data-driven guide for quality assurance, enabling timely interventions and reducing accidents caused by faulty temporary equipment. Furthermore, the framework’s adaptable design demonstrates strong potential for replicability across diverse construction sites and for other types of defects, paving the way for more effective, technology-driven safety protocols.",
    category: "SCI",
    keywords: "Cloud database; temporary equipment; quality inspection; construction safety; online management system"
  },
  {
    title: "BIM log mining framework using deep learning for productivity assessment in construction facilities",
    main_author: "Ali Akbar",
    co_authors: "장영희, 송진우, 이서준, 박상현, 배진현, 권순욱",
    journal: "Journal of Asian Architecture and Building Engineering",
    year: "2025",
    doi: "doi.org/10.1080/13467581.2025.2508442",
    abstract: "Assessing construction productivity objectively and in real-time remains challenging. This study proposes an automated framework leveraging Building Information Modeling (BIM) interaction logs and predictive modeling. The methodology involves systematic log data processing and feature engineering, generation of pseudo-label productivity scores derived from an initial expert-informed model, and a rigorous comparative evaluation of predictive architectures. Sixteen diverse models were evaluated using 10-fold cross-validation on a 500-instance dataset derived from construction logs. The cross-validation identified XGBoost as the top-performing architecture (R2 = 0.97 ± 0.01), demonstrating the effectiveness of gradient boosting on the engineered tabular features. The framework incorporates an integrated interface with visualization and natural language processing for enhanced insight generation and accessibility. While acknowledging limitations concerning pseudo-label usage and initial data processing steps, this research presents a robust, validated methodology for data-driven productivity assessment, offering a scalable alternative to traditional methods in construction project management.",
    category: "SCI",
    keywords: "Building information modeling (BIM); deep learning architectures; construction productivity; BIM log mining; LSTM autoencoder"
  },
  {
    title: "Amending Construction Workforce Skills Grade System - Improvement of Working Days for Systematic Management of Construction Worker's Skill -",
    main_author: "설준성",
    co_authors: "장영희, 박수훈, 이태호, 박준선, 이규협, 권순욱",
    journal: "한국건설관리학회",
    year: "2024",
    doi: "doi.org/10.6106/KJCEM.2025.26.2.103",
    abstract: "The skill grade system in the construction industry was introduced to address a decline in the active workforce, caused by an aging labor force and insufficient new recruits. This shortage has led to an imbalance in the supply and distribution of skilled labor across construction sites. The system was designed to stabilize job prospects and improve employment opportunities for workers. A key factor in managing skill grades is the average number of working days per year, which varies based on on-site experience, education, training, qualifications, and certifications. The system covers sixty occupations, each with its own standard for working days. However, the database includes inactive workers with fewer working days, which can skew the overall average. To refine these standards, surveys were conducted to gather workers' opinions on actual working days in each occupation. Additionally, data from the Korea Meteorological Administration was analyzed. These findings led to the establishment of more realistic reference days for each occupation, which were incorporated into the skill grade system. The revised standards were then validated through graphical simulations, assessing both current and projected skill grade distributions over the next five and ten years. This approach ensures the system remains effective in addressing the labor shortages and evolving workforce dynamics in the construction industry.",
    category: "KCI",
    keywords: "Skill Grade System; Construction Workforce Management; Skill Grade Calculation"
  },
  {
    title: "Augmented Reality-Based BIM Data Compatibility Verification Method for FAB Digital Twin implementation",
    main_author: "송진우",
    co_authors: "박상현, 이규협, 배지현, 권순욱, 조청석, 정수완",
    journal: "Buildings",
    year: "2023",
    doi: "doi.org/10.3390/buildings13112683",
    abstract: "By expanding the effective distance of compatibility between the AR model and the actual object, it was possible to increase the AR application range between the 3D virtual object model and the test target model and to improve the compatibility.",
    category: "SCI",
    keywords: "extended reality (XR); augmented reality (AR); building information modeling (BIM); fabrication facility (FAB); digital twin"
  },
  {
    title: "Object Detection and Distance Measurement Algorithm for Collision Avoidance of Precast Concrete Installation during Crane Lifting Process",
    main_author: "Yik Pong Yong",
    co_authors: "이서준, 장영희, 이규협, 권순욱, 조청석, 정수완",
    journal: "Buildings",
    year: "2023",
    doi: "doi.org/10.3390/buildings13102551",
    abstract: "Specifically, the object detection technique was used with the application of an Internet Protocol (IP) camera to detect the workers within the crane operation radius, whereas ultrasonic sensors were used to measure the distance of surrounding obstacles. Both applications were designed to work concurrently so as to prevent potential collisions during crane lifting operations. The field testing and evaluation of the integrated system showed promising results.",
    category: "SCI",
    keywords: "object detection; computer vision; distance measurement sensor; precast concrete; off-site construction; collision avoidance; crane"
  },
  {
    title: "Deep Learning-Based PC Member Crack Detection  and Quality Inspection Support Technology for the Precise Construction of OSC Projects",
    main_author: "이서준 ",
    co_authors: "정민경, 조청석, 박재원, 권순욱",
    journal: "Applied Sciences",
    year: "2022",
    doi: "doi.org/10.3390/app12199810",
    abstract: "It is expected that through optimizing and upgrading our proposed system, quality work for the precise construction of OSC projects can be ensured. At the same time, systematic and accurate quality management of OSC projects is achievable through inspection data. In addition, the smart quality inspection system is expected to establish a smart work environment that enables efficient and accurate quality inspection practices if applied to various construction activities other than the OSC projects.",
    category: "SCI",
    keywords: "off-site construction (OSC); precast concrete (PC) member; deep learning; Convolutional Neural Network (CNN); crack detection automation; AI (Artificial Intelligence)"
  },
  {
    title: "Synthetic Data and Computer-Vision-Based Automated Quality Inspection System for Reused Scaffolding",
    main_author: "Kim Alexander ",
    co_authors: "이규협, 이서준, 송진우, 권순욱, 정수완",
    journal: "Applied Sciences",
    year: "2022",
    doi: "doi.org/10.3390/app121910097",
    abstract: "Further, the resulting datasets were processed using artificial intelligence algorithms to obtain information about defect type, size, and location. Finally, the tested parts’ quality classes were calculated based on the obtained defect values.",
    category: "SCI",
    keywords: "computer vison; semantic segmentation; scaffolding; synthetic dataset; AI"
  },
  {
    title: "Analysis of accuracy factor and pre-processing methodology of image compensation for 3D reconstruction using 2D image obtained from unmanned aerial vehicle (UAV)",
    main_author: "문대윤 ",
    co_authors: "이규협 , 고형렬 , 권순욱 , 이서준 ",
    journal: "JAABE(Journal of Asian Architecture and Building Engineering)",
    year: "2021",
    doi: "doi.org/10.1080/13467581.2021.1971679",
    abstract: "Analysis of accuracy factor and pre-processing methodology of image compensation for 3D reconstruction using 2D image obtained from unmanned aerial vehicle (UAV)",
    category: "SCI",
    keywords: "UAV, photogrammetry as-built model, imapge compensation, point cloud"
  },
  {
    title: "Augmented reality and digital twin system for interaction with construction machinery",
    main_author: "Mobeen ",
    co_authors: "이규협 , 문대윤 , 권순욱 , 송진우 , 이서준 ",
    journal: "JAABE(Journal of Asian Architecture and Building Engineering)",
    year: "2021",
    doi: "doi.org/10.1080/13467581.2020.1869557",
    abstract: "Augmented reality and digital twin system for interaction with construction machinery",
    category: "SCI",
    keywords: "CPS, AR ,DT, construction, Equipment"
  },
  {
    title: "BIM Environment Based Virtual Desktop Infrastructure (VDI) Resource Optimization System for Small to Medium-Sized Architectural Design Firms",
    main_author: "이규협 ",
    co_authors: "신중환 , 권순욱 , 조청석 , 정수완 ",
    journal: "Applied Sciences",
    year: "2021",
    doi: "doi.org/10.3390/app11136160",
    abstract: "Specifically, after an analysis was carried out to see if the VDI system utilized in other industries may resolve the hindrance faced with the BIM environment in the construction industry, the KBimVdi system was created based on an algorithm for estimating server scales by analyzing the VDI system suitable for the BIM work environment. This was followed by a validation of the KBimVdi system based on selected projects carried out by small to medium-sized architectural firms where BIM was used for design work.",
    category: "SCI",
    keywords: "BIM; VDI (virtual desktop infrastructure); design organization; cloud computing"
  },
  {
    title: "Smart Facility Management System Based on Open BIM and Augmented Reality Technology",
    main_author: "정수완 ",
    co_authors: "조청석 , 송진우 , 이규협 , 이서준 , 권순욱 ",
    journal: "Applied Sciences",
    year: "2021",
    doi: "doi.org/10.3390/app112110283",
    abstract: "The results of this system’s creation and validation showed that the proposed AR-based smart FMS demonstrated faster and easier access to information compared with existing 2D blueprint-based FM work, while information obtained through AR allowed for immediate, more visual and easier means to express the information when integrated with actual objects.",
    category: "SCI",
    keywords: "augmented reality (AR); building information modeling (BIM); facility management (FM); mobile application"
  },
  {
    title: "Assessment of BIM Competencies and Correlation Analysis between Competencies and Career Characteristics of FAB Construction Project Participants",
    main_author: "이송이 ",
    co_authors: "정수완 , 권순욱 , 조청석 , 이규협 ",
    journal: "Applied Sciences",
    year: "2021",
    doi: "doi.org/10.3390/app11188468",
    abstract: "As a result, high correlations were found between BIM competencies and BIM-based FAB construction project experience for the owner group, whereas competency items related to BIM-based construction project experience showed high correlations for the designer group.",
    category: "SCI",
    keywords: "fabrication facility (FAB); construction project; BIM; competency; competency assessment"
  },
  {
    title: "Automatic Space Analysis Using Laser Scanning and a 3D Grid: Applications to Industrial Plant Facilities",
    main_author: "김동현 ",
    co_authors: "권순욱 , 조청석 , Borja Garcia de Soto , 문대윤 ",
    journal: "Sustainability",
    year: "2020",
    doi: "doi.org/10.3390/su12219087",
    abstract: "The proposed method of this study is expected to help solve the problems derived from arrangement and installation of new equipment in a complex plant site.",
    category: "SCI",
    keywords: "3D grid; 3D shape scanning; equipment and facilities relocation; space analysis; point cloud"
  },
  {
    title: "A discrepancy analysis of BIM-based quantity take-off for building interior components",
    main_author: "김성아 ",
    co_authors: "진상윤 , 권순욱 ",
    journal: "Journal of Management in Engineering",
    year: "2019",
    doi: "doi.org/10.1061/(ASCE)ME.1943-5479.0000684",
    abstract: "Results indicate that the QD occurs non-sequentially and exceeds the loss rates for some interior materials. Furthermore, this study identifies the causative factors of the QD by common features observed in the particular materials and suggests modeling and measurement strategies for minimizing QD.",
    category: "SCI",
    keywords: "Earthwork, Terrestrial LiDAR, UAV, Image processing, Pointcloud"
  },
  {
    title: "Comparison and utilization of point cloud generated from photogrammetry and laser scanning: 3D world model for smart heavy equipment planning",
    main_author: "문대윤 ",
    co_authors: "정수완 , 권순욱 , 서정원 , 신중환 ",
    journal: "Automation in Construction",
    year: "2019",
    doi: "doi.org/10.1016/j.autcon.2018.07.020",
    abstract: "Therefore, this study proposed a method for generating and merging hybrid point cloud data acquired from laser scanning and UAV-based image processing. In addition, a comparison was conducted between the datasets acquired from laser scanning and image processing, using examples from some case studies. Finally, an analytical comparison was performed to verify the accuracy of the UAV-based image processing technology for earthwork projects.",
    category: "SCI",
    keywords: "Building information modeling; Component; Quantity take-off; Discrepancy; Compositely modeled object; Individuallymodeled object."
  },
  {
    title: "A Study on Method of Vertical Zoning of Construction Lift for High-rise Building based on Lift Planning & Operation History Database",
    main_author: "신중환 ",
    co_authors: "권순욱 , 문대윤 , 정수완 , 이규협 ",
    journal: "대한토목학회",
    year: "2018",
    doi: "doi.org/10.1007/s12205-017-1374-3",
    abstract: "This simulation based decision making tool reduces the user’s queuing time compared with the previous system. This system is expected to contribute to high-rise building construction of over 400 m.",
    category: "SCI",
    keywords: "Construction lift, vertical zoning, ELIS"
  },
  {
    title: "A study on scan data matching for reverse engineering of pipes in plant construction",
    main_author: "이미나 ",
    co_authors: "이성기 , 권순욱 , 진상윤 ",
    journal: "대한토목학회",
    year: "2017",
    doi: "doi.org/10.1007/s12205-016-0929-z",
    abstract: "in this study, a reverse engineering algorithm is proposed, which can measure the preciseness of pipes, by comparing the 3D CAD model and the 3D shape information obtained from a laser scanner. Applying the algorithm can contribute to re-construction prevention and quality control in the construction process.",
    category: "SCI",
    keywords: "3D Point, ICP, matching algorithm, 3D laser scanner"
  },
  {
    title: "A comparative study of noise elimination algorithms for a 3D terrain model through object clustering and the differential method",
    main_author: "유현석 ",
    co_authors: "김영석 , 권순욱 ",
    journal: "대한토목학회",
    year: "2015",
    doi: "doi.org/10.1007/s12205-013-0370-5",
    abstract: "It is expected that the noise elimination algorithm proposed in this study will be very useful as a widely used essential technology required for the development of automated technology not only in earthwork field but also in other general construction and civil engineering fields by noise elimination of the 3D working environment model.",
    category: "SCI",
    keywords: "stereo vision, noise algorithm, 3D model"
  },
  {
    title: "Measures to expand market inroads into the Vietnamese construction market",
    main_author: "유정호 ",
    co_authors: "장현승 , 권순욱 , 손보식 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.1007/s12205-013-0351-8",
    abstract: "According to the analysis results, general building projects and infrastructure projects in Vietnam in the long term are projected to expand from the currently dominant private investment projects, to a larger scope, along with the increase of public investments. In particular, as for public investments in the general building field, market entries will be smoother in the form of Public-Private Partnership.",
    category: "SCI",
    keywords: ""
  },
  {
    title: "A MEMS-based commutation module with vibration sensor for wireless sensor network-based tunnel-blasting monitoring",
    main_author: "김정열 ",
    co_authors: "권순욱 , 박승희 , 김영석 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.1007/s12205-013-0108-4",
    abstract: "The authors have designed both a sensor device, and a sensor module having wireless communication capability built around it, and tested them in real-world tunnels, as well as in test labs. The test results showed that our prototype performed adequately for its intended use.",
    category: "SCI",
    keywords: "Lift simulation, optimization planning, construction hoist"
  },
  {
    title: "Development of automated pipe spool monitoring system using RFID and 3D model for plant construction project",
    main_author: "김창환 ",
    co_authors: "권순욱 , 조창연 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.1007/s12205-013-0111-9",
    abstract: "This research aims to develop a real-time pipe tracking system for plant construction, utilizing state-of-the-art technologies such as RFID and 3D digital models on a handheld mobile device, which allows more efficient task management than a conventional computer.",
    category: "SCI",
    keywords: "Automatic construction, merging algorithm, 3D laser scanner"
  },
  {
    title: "Development of piezoelectric energy harvesting modules for impedance-based wireless structural health monitoring system",
    main_author: "박승희 ",
    co_authors: "이창길 , 김효정 , 윤홍식 , 권순욱 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.1007/s12205-013-0225-0",
    abstract: "Therefore, a time delay circuit and reset IC chip was used to improve the efficiency of the electrical power generated. The experimental results were used to estimate the efficiency of these devices and identified the feasibility of their use in practical applications.",
    category: "SCI",
    keywords: "Construction market, marketability, competitiveness"
  },
  {
    title: "Innovative Sensing for Built Environment Preface",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "Automation in Construction",
    year: "2013",
    doi: "doi.org/10.1016/j.autcon.2013.01.002",
    abstract: "",
    category: "SCI",
    keywords: "vibration sensor, tunnel, MEMS"
  },
  {
    title: "An optimal algorithm of the multi-lifting operating simulation for super-tall building construction",
    main_author: "조창연 ",
    co_authors: "이유섭 , 조문영 , 권순욱 , 신윤석 , 이준복 ",
    journal: "Automation in Construction",
    year: "2013",
    doi: "doi.org/10.1016/j.autcon.2013.01.003",
    abstract: "The suggested algorithm is verified through simulation technique, and finally quantitative and systematic methods of lifting operation are proposed.",
    category: "SCI",
    keywords: "pipe tracking, RFID, plant construction"
  },
  {
    title: "Development of optimized point cloud merging algorithms for accurate processing to create earthwork site models",
    main_author: "권순욱 ",
    co_authors: "이미나 , 이문주 , 이석한 , 이준복 ",
    journal: "Automation in Construction",
    year: "2013",
    doi: "doi.org/10.1016/j.autcon.2013.01.004",
    abstract: "To develop accurate and fast merging algorithms, ICP (Iterative Closest Point)-based merging algorithms and normal vectors were applied. Algorithms to merge the two models and to reflect the characteristics of the necessary earthwork will be proposed.",
    category: "SCI",
    keywords: "energy harvesting, piezoeletric materiall, ambient vibration"
  },
  {
    title: "A service-oriented integrated information framework for RFID/WSN-based intelligent construction supply chain management",
    main_author: "신태홍 ",
    co_authors: "진상윤 , 윤수원 , 권순욱 ",
    journal: "Automation in Construction",
    year: "2011",
    doi: "doi.org/10.1016/j.autcon.2010.12.002",
    abstract: "The result of this research is expected to be utilized effectively as a basic framework to manage information in RFID/WSN based construction supply chain management (CSCM) environments.",
    category: "SCI",
    keywords: "SOA, construction supply chain management, FRID"
  },
  {
    title: "A development of next generation intelligent construction liftcar toolkit for vertical material movement management",
    main_author: "조창연 ",
    co_authors: "권순욱 , 신태홍 , 진상윤 , 김예상 ",
    journal: "Automation in Construction",
    year: "2011",
    doi: "doi.org/10.1016/j.autcon.2010.07.008",
    abstract: "To support the system, a hoist-mountable intelligent toolkit was developed. Its feasibility test was conducted by applying the implemented system to a test bed and then analyzing efficiency of the system and the toolkit.",
    category: "SCI",
    keywords: "construction lift, material management, RFID"
  },
  {
    title: "디지털 트윈 & IoT Sensing 융합 기반 전통시장 화재 모니터링 시스템",
    main_author: "홍정택 ",
    co_authors: "이규협 , 송진우 , 이서준 , 장영희 , 권순욱",
    journal: "한국산업융합학회",
    year: "2023",
    doi: "doi.org/10.21289/KSIC.2023.26.6.1251",
    abstract: "In this study, gas detection sensors and flame detectors are additionally installed in Gwangmyeong Traditional Market, and a digital twin-based traditional market fire monitoring system is implemented in conjunction with existing sensors in the market's 3D model. With this digital twin based fire monitoring system, we can reduce the malfunctions of fire detect sensors, and can easily guide the evacuation route.",
    category: "KCI",
    keywords: "Digital Twin , IoT , Traditional Market , Fire Monitoring System"
  },
  {
    title: "국내 발주지침 보완을 통한 토목분야 BIM 활성화 전략 제안",
    main_author: "최고은 ",
    co_authors: "이재욱 , 홍창희 , 문현석 , 김도영",
    journal: "한국BIM학회",
    year: "2023",
    doi: "doi.org/10.13161/kibim.2023.13.2.047",
    abstract: "This study aims to contribute to creating an environment in which construction practitioners who have no experience in BIM project can efficiently carry out BIM projects.",
    category: "KCI",
    keywords: "Civil BIM , Procurement , Request for Proposal , Road , Guideline"
  },
  {
    title: "실시간 건설 장비 정보 및 현장 센싱 정보 기반 CONS-DT(CONSTRUCTION SITE DIGITAL TWIN)",
    main_author: "홍정택 ",
    co_authors: "이규협 , 송진우 , 이서준 , 권순욱",
    journal: "한국건설자동화로보틱스학회",
    year: "2022",
    doi: "doi.org/10.55785/JCAR.1.1.22",
    abstract: "본 연구에서는 건설 공사 시 현장 및 장비 정보 습득과 분석을 통하여, 보다 효율적이고 정확한 현장관리와 건설 장비 제어를 위해 실시간 건설 장비 정보 및 현장 센싱 정보 기반 CONS-DT 실시간 현장 관리 시스템을 구축하였다.",
    category: "KCI",
    keywords: "디지털 트윈 , 스마트 건설 , IoT , 시공관리 , 3D Point Cloud , AR"
  },
  {
    title: "행정중심복합도시 환경영향 분석 및 거주 후 평가 지표수립에  관한 연구",
    main_author: "이규협 ",
    co_authors: "전병철 , 정수완 , 권순욱 ",
    journal: "한국콘텐츠학회",
    year: "2022",
    doi: "doi.org/10.5392/JKCA.2022.22.03.500",
    abstract: "본 연구는 대규모 단위의 행정중심복합도시에 대해 거주 후 평가(POE) 연구 활동을 수행하였다.",
    category: "KCI",
    keywords: "거주 후 평가 , 만족도 분석 , 행정중심복합도시 , 신도"
  },
  {
    title: "하이테크 공장 건설 사업비 예측 정확도 향상을 위한 공장 생산량 기반 세부 공사별 보정계수 도출",
    main_author: "최성훈 ",
    co_authors: "김진철 , 오재영 , 권순욱",
    journal: "한국콘텐츠학회",
    year: "2021",
    doi: "doi.org/10.5392/JKCA.2021.21.11.203",
    abstract: "본 연구에서는 하이테크 산업 공사의 특성을 반영하여, 공장 전체 생산량을 고려하여 전체라인 구성을 위한 공사 유형과 빠른 생산가동을 위한 기본라인 구성을 위한 공사 유형으로 기존 공사내역을 분류하였으며, 비교·분석을 통하여 기본라인 구성 유형 공사비 산출을 위한 공사별, 세부 공사별 보정 비율을 도출하였다. 신규 하이테크 공장 건설 프로젝트에 본 연구에서 제시한 보정 비율을 적용하여 신뢰성 및 정확도를 검증하였다.",
    category: "KCI",
    keywords: "High-Tech Factory , Cost Estimating , Correction Ratio/Value"
  },
  {
    title: "하이테크 공장의 효율적 건설 사업비 분석 및 예측을 위한 WBS·CBS 기반 건설정보 분류체계 구축",
    main_author: "최성훈 ",
    co_authors: "김진철 , 권순욱 ",
    journal: "한국콘텐츠학회",
    year: "2021",
    doi: "doi.org/10.5392/JKCA.2021.21.08.356",
    abstract: "본 연구의 목적은 국내 건설된 관련 프로젝트 데이터를 수집·분류·분석을 통하여 하이테크 공장 건설에 적합한 건설정보 분류체계를 구성하는 데 있다. 본 연구를 통해 분류·분석된 WBS(Work Breakdown Structure)·CBS(Cost Breakdown Structure)를 기반으로 계층적 구분을 통한 코드체계를 제안하였고, WBS와 CBS를 연계를 통한 건축물의 비용 모델을 입체화 및 활용 방법을 제시하였다.",
    category: "KCI",
    keywords: "건설정보분류 , WBS , CBS , 하이테크 공장"
  },
  {
    title: "스마트 디바이스 기반 유지보수 관리자용 자동화 모델 구축에 관한 연구",
    main_author: "박지환 ",
    co_authors: "정수완 , 이서준 , 송진우 , 권순욱 ",
    journal: "한국건설관리학회",
    year: "2021",
    doi: "doi.org/10.6106/KJCEM.2021.22.1.072",
    abstract: "본 연구는 스마트 디바이스 기반의 자동화 모델 구축을 위하여, ① 일반적인 시설물 관리 프로세스 분석 및 관련 문헌 검토, ② 현재 유지보수 프로세스 개선, ③BIM Data, COBie Data, IoT 및 AR 기술을 기반으로 유지보수 관리 자동화 모델 기능 구성도 제작, ④ 스마트 디바이스 기반 유지보수 관리 자동화 모델 구축, ⑤ 사례 현장 적용, 유지보수 관리 진행 및 이력정보 재검토 소요 시간 비교를 통한 시스템 검증을 실시하였다.",
    category: "KCI",
    keywords: "건물 유지보수 , 자동화 모델 , COBie Data , BIM Data , 스마트 건설"
  },
  {
    title: "스마트 건설의 최신 트렌드와 건설산업의 대응전략",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "한국건설관리학회",
    year: "2021",
    doi: "",
    abstract: "",
    category: "KCI",
    keywords: ""
  },
  {
    title: "국내 건설공사에서 공기지연 분석방법 적용 사례 분석",
    main_author: "김선규 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2019",
    doi: "doi.org/10.6106/KJCEM.2019.20.6.098",
    abstract: "본 연구의 목적은 국내 건설공사의 공정관리 현실에 적합한 공기지연 분석방법을 제시함으로써, 향후 국내 건설공사의 공기지연관련 분쟁과 소송에서 의미 있는 참고자료로 활용될 수 있도록 하는 것이다.",
    category: "KCI",
    keywords: "공기지연 , CPM 공정표 , 계획공정 분석법 , 계획공정 대비 완료공정 분석법"
  },
  {
    title: "건설산업 혁신을 위한 증강현실(AR)/ 가상현실(VR) 기술의 활용 및 전망 = Trend of Augmented Reality/Virtual Reality Technology for Innovation in The Construction Industry",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "한국BIM학회",
    year: "2018",
    doi: "",
    abstract: "",
    category: "KCI",
    keywords: ""
  },
  {
    title: "가상 데스크톱 인프라 (VDI) 기술을 활용한 중소규모 설계사의 BIM 사용자 별 데스크탑 자원 할당 전략에 관한 연구",
    main_author: "이규협 ",
    co_authors: "신중환 , 권순욱 , 박재우 ",
    journal: "한국건설관리학회",
    year: "2016",
    doi: "doi.org/10.6106/KJCEM.2016.17.5.078",
    abstract: "본 연구에서는 이러한 문제 중에서 BIM 운영관리를 위해 필요한 인프라 구축 및 유지비용 절감 방안으로 타 산업에서 최근 적용이 모색되고 있는 클라우드 컴퓨팅 기술 중 하나인 VDI 시스템을 BIM 분야에 적용하기 위한 연구를 수행하였다.",
    category: "KCI",
    keywords: "BIM , 데스크탑 가상화 인프라 , 클라우드 컴퓨팅 , 설계 조직"
  },
  {
    title: "국내 협업 설계 환경에서의 IFC 기반 정보 교환 프레임워크 구축에 관한 연구",
    main_author: "신중환 ",
    co_authors: "권순욱 , 이규협 , 최상덕 , 김진만 ",
    journal: "한국건설관리학회",
    year: "2015",
    doi: "doi.org/10.6106/KJCEM.2015.16.1.024",
    abstract: "협업 설계 프로세스 내 원활한 정보 교환의 저해 요인 분석을 통해 본 연구는 Open-API와 IFC기반의 BIM 협업 지원 시스템을 제안한다. BIM 무결성 피드백 시스템이라 명명된 API 솔루션은 IFC 기반의 데이터 교환에서 발생하는 상호 불일치성을 판별하고 report를 작성해 주는 기능을 수행한다.",
    category: "KCI",
    keywords: "BIM , 협업설계 , 정보교환 , IFC , 협업지원 툴"
  },
  {
    title: "클라우드 컴퓨팅 기술을 활용한 데스크탑 가상화 기반의 BIM 설계 환경 구축에 관한 연구",
    main_author: "신중환 ",
    co_authors: "이규협 , 권순욱 , 최규성 , 고형렬 ",
    journal: "한국건설관리학회",
    year: "2015",
    doi: "doi.org/10.6106/KJCEM.2015.16.4.118",
    abstract: "본 논문은 VDI 시스템 환경 설정 및 구축을 통해 BIM 모델링, Viewing, 모델 체크, 마크업 등 BIM을수행할 수 있는 서버 인프라 서비스 구축 방안을 제시한다.",
    category: "KCI",
    keywords: "BIM , 데스크탑 가상화 인프라 , 클라우드 컴퓨팅 , 설계 조직"
  },
  {
    title: "리모델링 프로젝트의 역설계 적용을 위한 최적 3 차원 레이저 스캐닝정보 획득 방안에 관한 연구",
    main_author: "이상설 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2014",
    doi: "doi.org/10.6106/KJCEM.2014.15.3.003",
    abstract: "본 연구에서는 실험을 통해 역설계 과정 중 3차원 형상 정보를 획득하는데 있어서 포인트 데이터 정밀도에 따른 측정시간과 오차를 분석하여 최적의 포인트 데이터 획득 정밀도를 제안하고자 한다.",
    category: "KCI",
    keywords: "역설계 , 실내 리모델링 , 3차원 형상 정보 획득 , 레이저 스캐너"
  },
  {
    title: "NFC (Near Field Communication) 와 증강현실 기술을 활용한모바일 기반 플랜트 배관공사관리 프로세스 체계 구축",
    main_author: "문대윤 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2014",
    doi: "doi.org/10.6106/KJCEM.2014.15.2.122",
    abstract: "본 연구에서는 효율적인 배관공사관리를 위한 모바일 기반의 NFC, AR기술을 활용하여 프로세스 개선 및 시스템 구축하였다.",
    category: "KCI",
    keywords: "배관공사관리 , 근거리통신 , 증강현실 모바일 기기"
  },
  {
    title: "BIM 기반의 초고층 빌딩 내부마감 개략견적 코스트모델 개발",
    main_author: "정수완 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2014",
    doi: "doi.org/10.6106/KJCEM.2014.15.2.053",
    abstract: "국내 복합용도 프로젝트 공사비 예측기술 및 관리기술 발전을 위하여 BIM의 공간정보를 활용한 내부마감 개략견적 코스트 모델을 개발하여 제시하였다.",
    category: "KCI",
    keywords: "공사비 , 초기사업비예측 , 코스트모델"
  },
  {
    title: "스마트 리프트 모니터링 및 제어기술",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "한국건설관리학회",
    year: "2014",
    doi: "",
    abstract: "",
    category: "KCI",
    keywords: ""
  },
  {
    title: "센싱정보를 활용한 초고층 건설용 리프트 최적화 운행 시스템 개발",
    main_author: "신중환 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2013",
    doi: "doi.org/10.6106/KJCEM.2013.14.5.153",
    abstract: "본 논문에서는 건설용 리프트 운영 효율증대를 위하여 센서를 사용한 리프트 운행 정보를 수집하고 실시간 분석이 가능한 건설용 리프트 최적화 운행 시스템 개발을 실시 및 검증 단계를 수행하여, 양중 효율의 지표가 되는 사용자 대기 시간의 단축을 도모하고 향후 무인 스마트 리프트의 초석이 되는 시스템을 제시하고자 한다.",
    category: "KCI",
    keywords: "건설용 리프트 , ELIS(Embedded Lift Information System) , 최적 리프트 카 선정 프로세스"
  },
  {
    title: "클라우드 컴퓨팅 기반 BIM 서비스를 위한 BIM 서버 기반의 뷰어 개발",
    main_author: "윤수원 ",
    co_authors: "김병곤 , 최종문 , 권순욱 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.12652/Ksce.2013.33.4.1719",
    abstract: "본 연구는 BIM 운영을 위해 필요한 인프라 구축 비용 절감과 국내 프로세스에 맞는 다양한 BIM 서비스 제공을 위한 방안으로 클라우드 컴퓨팅 기술과 BIM을 접목하는 것을 제안하고, 이를 위한 수요 조사를 바탕으로, 클라우드 컴퓨팅을 이용한 인프라 비용 절감(IaaS 구축)을 위한 IFC 기반 BIM 서버와 맞춤형 서비스(SaaS 제공)를 위한 Viewer를 개발하였다.",
    category: "KCI",
    keywords: "건설정보기술 , BIM , 클라우트 컴퓨팅 , 클라우드 기반 BIM 서비스 , BIM 서버 기반 Viewer , 3차원 설계"
  },
  {
    title: "지능형 굴삭 로봇의 개발을 위한 로컬영역 3 차원 모델링 센서 선정 및 현장 적용성 분석에 관한 연구",
    main_author: "유현석 ",
    co_authors: "권순욱 , 김영석 ",
    journal: "대한토목학회",
    year: "2013",
    doi: "doi.org/10.12652/Ksce.2013.33.6.2551",
    abstract: "이 연구에서는 지능형 굴삭 로봇의 로컬영역 3차원 모델링을 위하여 현재까지 개발된 3차원 작업환경 모델링 센서의 기술 사양과 장단점을 분석하고, AHP 분석을 통하여 센서별 적용가능성을 분석한다.",
    category: "KCI",
    keywords: "지능형 굴삭 로봇 , 3D 모델링 센서 , 로컬영역 , 토공사 , 작업지형"
  },
  {
    title: "Double Sensor Type 감지장치를 통한 리프트 정지위치 오차누적 개선 방안 제안",
    main_author: "이종현 ",
    co_authors: "권순욱 , 박성응 , 이미나 ",
    journal: "한국건설관리학회",
    year: "2012",
    doi: "doi.org/10.3106/KJCEM.2012.13.2110",
    abstract: "본 연구에서는 리프트 정지위치 에러에 의한 시간 및 비용 손실을 방지하기 위해 리프트 정지위치 감지장치를 개발하였다. 실험을 통해, 정지위치 에러 발생 시 이를 보정하는 기능을 검증하였고, 정확도도 약 9.75mm 증가하는 것을 확인하였다.",
    category: "KCI",
    keywords: "리프트 정지위치 감지장치 , 리프트 모니터링 , 리프트 오차누적 방지"
  },
  {
    title: "교차영향분석을활용한건설업무기능및공종별주요 IT 기술도출",
    main_author: "박성훈 ",
    co_authors: "권순욱 , 김영석 ",
    journal: "한국건설관리학회",
    year: "2012",
    doi: "doi.org/10.6106/KJCEM.2012.13.1.160",
    abstract: "본 논문에서는 건설 전(全) 프로세스와 관련하여 포괄적 관점에서 융합기술을 분석하여, 건설IT융합 모델 개발 및 활용방향의 지표가 될 수 있는 프로세스 단계 별 적합한 유망 IT기술을 도출하고 나아가 효과적인 건설IT융합의 기본방향을 제시하고자 한다.",
    category: "KCI",
    keywords: "시나리오 기법(Scenario planning) , 교차영향분석(Cross-Impact) , 중요도-만족도 분석 , 건설-IT융합"
  },
  {
    title: "BSA 기법을 활용한 사업유형별 베트남 건축시장 진출 역량 평가",
    main_author: "장현승 ",
    co_authors: "권순욱 ",
    journal: "대한건축학회",
    year: "2012",
    doi: "",
    abstract: "The results of this study were as follows; supply chain management, supplier relationship management, and brand marketing power are needed for public tender projects and F/S, global project financing, and economic analysis are needed for construction investment projects.",
    category: "KCI",
    keywords: "편익구조분석 , 전문가그룹토론 , 베트남건축시장"
  },
  {
    title: "Factor analysis of construction practices for infrastructure projects in Korea",
    main_author: "박희성 ",
    co_authors: "권순욱 ",
    journal: "대한토목학회",
    year: "2011",
    doi: "doi.org/10.1007/s12205-011-1064-5",
    abstract: "The critical success factors presented in this paper can be used as a check list to prepare and implement public infrastructure projects in Korea. Furthermore, it will also provide information on general concepts involved in the preparations of international construction projects.",
    category: "그 외",
    keywords: "project management , infrastructure , best practices , statistical analysis"
  },
  {
    title: "IPD 도입을 위한국내 건설기술자의 인식 분석",
    main_author: "송설민 ",
    co_authors: "김예상 , 진상윤 , 권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "",
    abstract: "본 연구는 국내의 경우에도 통합적인 프로젝트 관리를 위한 IPD의 도입 필요성이 커짐에 따라 실질적 도입 이전에 IPD의 개념과 원칙을 바탕으로 하여 도출된 핵심가치를 중심으로 건설업종에 종사하는 실무자들의 건설환경에 대한 현황과 인식을 파악하여 IPD의 도입을 위한 제약요인들을 파악하는 것을 목적으로 향후 IPD 관련 연구의 기초자료로 활용될 것으로 기대된다.",
    category: "그 외",
    keywords: "프로젝트통합발주체계(IPD) , 발주체계 , 계약방식 , 제도개선"
  },
  {
    title: "Analysis of success factors in construction IT convergence: applying AHP",
    main_author: "임정아 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "doi.org/10.6106/KJCEM.2011.12.4.130",
    abstract: "본 연구에서는 건설·IT 융합 산업의 활성화를 위해 건설·IT융합 사업의 성공요인과 그 중요도를 도출하여 건설·IT융합 성공사례의 평가기준을 제시하는 것을 목적으로 한다.",
    category: "그 외",
    keywords: "융합 , 성공요인 , 건설·IT융합 산업 , AHP"
  },
  {
    title: "U-City 사업 계획단계에서의 핵심 리스크 요인도출",
    main_author: "김호기 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "doi.org/10.6106/KJCEM.2011.12.4.139",
    abstract: "본 연구에서는 u-City 사업의 지속적인 성장과 성공적인 수행을 위하여 계획단계에서의 문제점과 기존의 개발사업의 리스크 요인을 분석하여, u-City 계획단계에서 관리되어야 할 리스크 인자를 식별하고 이를 통계적 기법을 활용하여 리스크의 중요도, 발생확률, 발생영향에 따라 리스크 요인을 분석하여 정량화 하였다. 이를 통하여 우선적으로 관리되어야 할 핵심리스크 요인을 도출하였으며, u-City사업의 효과적인 리스크 관리를 위한 기초자료를 마련하였다.",
    category: "그 외",
    keywords: "리스크 평가 , 리스크 요인 , 사업계획단계 , 요인분석 , u-City"
  },
  {
    title: "USN technologies decision making matrix for the efficiency management of earthwork selection",
    main_author: "정승우 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "doi.org/10.6106/KJCEM.2011.12.5.55",
    abstract: "본 연구의 결과는 건설현장의 토공사 계측관리를 위해 USN기술 적용 시 상황에 맞는 기술을 선택 할 수 있는 판단의 기준 및 척도로 활용이 가능하며, USN기술 도입을 통해 현장의 지능화 및 관리 효율 극대화를 가져올 것으로 기대한다.",
    category: "그 외",
    keywords: "토공사 , 계측관리 , 유비쿼터스 센서 네트워크(USN) , 계층분석적방법(AHP) , 의사결정 지원모델"
  },
  {
    title: "건설현장에서 효율적인 USN (Ubiquitous Sensor Networks) 기술 활용을 위한 토공사 계측 관련 고려요소 분석 및 우선순위 도출",
    main_author: "정승우 ",
    co_authors: "김예상 , 진상윤 , 권순욱 ",
    journal: "대한건축학회",
    year: "2011",
    doi: "",
    abstract: "The results from this study will serve as decision-making aid for deploying the USN technology to future construction work sites.",
    category: "그 외",
    keywords: "건설안전 , 토공사 , 계측관리 , 유비쿼터스 센서 네트워크 , 계층분석적 의사결정방법"
  },
  {
    title: "효율적인 토공사 계측관리를 위한 USN 기술 선정 의사결정 매트릭스 도출",
    main_author: "정승우 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "doi.org/10.6106/KJCEM.2011.12.5.55",
    abstract: "본 연구의 결과는 건설현장의 토공사 계측관리를 위해 USN기술 적용 시 상황에 맞는 기술을 선택 할 수 있는 판단의 기준 및 척도로 활용이 가능하며, USN기술 도입을 통해 현장의 지능화 및 관리 효율 극대화를 가져올 것으로 기대한다.",
    category: "그 외",
    keywords: "토공사 , 계측관리 , 유비쿼터스 센서 네트워크(USN) , 계층분석적방법(AHP) , 의사결정 지원모델"
  },
  {
    title: "Deriving of Major Risk Factors for Planning Phase of u-City Project",
    main_author: "김호기 ",
    co_authors: "권순욱 ",
    journal: "한국건설관리학회",
    year: "2011",
    doi: "doi.org/10.6106/KJCEM.2011.12.4.139",
    abstract: "본 연구에서는 u-City 사업의 지속적인 성장과 성공적인 수행을 위하여 계획단계에서의 문제점과 기존의 개발사업의 리스크 요인을 분석하여, u-City 계획단계에서 관리되어야 할 리스크 인자를 식별하고 이를 통계적 기법을 활용하여 리스크의 중요도, 발생확률, 발생영향에 따라 리스크 요인을 분석하여 정량화 하였다. 이를 통하여 우선적으로 관리되어야 할 핵심리스크 요인을 도출하였으며, u-City사업의 효과적인 리스크 관리를 위한 기초자료를 마련하였다.",
    category: "그 외",
    keywords: "리스크 평가 , 리스크 요인 , 사업계획단계 , 요인분석"
  },
  {
    title: "A study on the framework construction of mobile ERP system based on smart-phone",
    main_author: "박정훈 ",
    co_authors: "임정아 , 권순욱 ",
    journal: "대한건축학회",
    year: "2010",
    doi: "",
    abstract: "In this research, the result shows the potential of the framework which can overcome the current problems of ERP system and suggest potential solution of mobile technology.",
    category: "그 외",
    keywords: "건설ERP , 건설ERP구축 , 모바일오피스 , 모바일ERP , 신기술기반건설ERP , 스마트폰"
  },
  {
    title: "초고층 건설현장의 USN 기술 적용대상 분석 및 우선순위 도출",
    main_author: "정승우 ",
    co_authors: "권순욱 , 조창연 ",
    journal: "대한건축학회",
    year: "2010",
    doi: "",
    abstract: "The authors surveyed several high-rise construction sites for finding out those items measurable with the ubiquitous sensor networks (USN) technology; using AHP analysis technique, potential influences of the individual items were analyzed for identifying their significance so that the new technology can be deployed to the higher priority ones first.",
    category: "그 외",
    keywords: "초고층 , 유비쿼터스 센서 네트워크 , 시설물관리 , 안전관리 , 계층분석적 의사결정방법"
  },
  {
    title: "Feasibility Analysis of Introducing CM at Risk Delivery Method to the Korean Public Construction Industry by Analyzing Attributes of the Projects",
    main_author: "고민혁 ",
    co_authors: "김예상 , 권순욱 , 진상윤 ",
    journal: "한국건설관리학회",
    year: "2010",
    doi: "doi.org/10.6106/KJCEM.2010.11.2.3",
    abstract: "본 연구에서는 'CM at Risk-GMP 방식', 'CM at Risk 방식-실비정산 방식'에 대한 특성요인 15가지를 도출하였으며, CM업계의 전문가를 대상으로 설문조사를 실시하여 각 유형에 대한 적합도를 분석하였다.",
    category: "그 외",
    keywords: "CM at Risk 방식 , CM at Risk-GMP 방식 , CM at Risk-실비정산 방식 , 발주방식의 특성요인"
  },
  {
    title: "공공건설사업 사후평가의 사업효율성 평가 개선방안에 관한 연구",
    main_author: "김호기 ",
    co_authors: "권순욱 , 이두현 , 박희성 , 박성훈 ",
    journal: "대한토목학회",
    year: "2010",
    doi: "",
    abstract: "본 연구에서는 현재 시행되고 있는 사후평가의 사업효율성을 평가하는 항목별(수요, 비용, 편익) 세부 절차 및 방법에 대하여 전문가들의 자문의견을 통하여 문제점을 도출하고, 도출된 문제점을 종합하여 개선방안을 제시하였다.",
    category: "그 외",
    keywords: ""
  },
  {
    title: "국내 사례분석을 통한 u-환경서비스의 개선 방안",
    main_author: "이종현 ",
    co_authors: "박성훈 , 류윤진 , 권순욱 ",
    journal: "한국통신학회",
    year: "2010",
    doi: "",
    abstract: "",
    category: "그 외",
    keywords: ""
  },
  {
    title: "소셜네트워크의 형성을 통한 u-Service 개선과정의 주민 참여 활성화 방안",
    main_author: "김호기 ",
    co_authors: "최윤길 , 류윤진 , 권순욱 , 진상윤 ",
    journal: "한국통신학회",
    year: "2010",
    doi: "",
    abstract: "본 논문에서는 u-서비스 도출, 운영, 개선에 이르는 전 과정에서 주민들의 참여를 활성화 할 수 있는 방안을 제시하고자 한다.",
    category: "그 외",
    keywords: ""
  },
  {
    title: "공공건축공사 사후평가 모델 개발: 공동주택을 중심으로",
    main_author: "김재우 ",
    co_authors: "권순욱 ",
    journal: "대한건축학회",
    year: "2009",
    doi: "",
    abstract: "This study is to propose and implement the following research for the post-evaluation model after drawing the lists which correspond to the objective of the public building to deduce the suitable and efficient post-evaluation list of the public construction.",
    category: "그 외",
    keywords: "사후평가 , 고객만족 , 계층적 분석 기법"
  },
  {
    title: "차세대 지능형 건설물류관리 프로세스 지원을 위한 지능형 장비 간 물류정보인식 메커니즘 개발",
    main_author: "권상혁 ",
    co_authors: "신태홍 , 진상윤 , 김예상 , 권순욱 , 윤수원 ",
    journal: "대한건축학회",
    year: "2009",
    doi: "",
    abstract: "The following research is based on the study of solutions of the problems that can occur when implementing USN based equipment for construction material distribution management by classifying problems and finding the best solution of material distribution reading mechanism through tests.",
    category: "그 외",
    keywords: "물류관리 , 물류정보인식 , 유비쿼터스 기술 , 지능형 장비 , 인식 메커니즘"
  },
  {
    title: "공동주택사업의 사후평가제도 사례 연구",
    main_author: "권순욱 ",
    co_authors: "박희성 ",
    journal: "대한건축학회",
    year: "2009",
    doi: "",
    abstract: "To figure out problems of the projects and to proposes recommendations, the paper surveyed the post evaluation reports of three apartment housing projects, and compared them with estimations to analyze the resultant post-built deviations from initially estimated values, in terms of cost and schedule.",
    category: "그 외",
    keywords: "사후평가 , 건설성과 , 건설 제도 , 공동주택"
  },
  {
    title: "RFID/USN 기반의 건설물류관리 프로세스 레퍼런스모델 개발 및 정보모델 개발",
    main_author: "이우재 ",
    co_authors: "신태홍 , 진상윤 , 김예상 , 권순욱 ",
    journal: "대한건축학회",
    year: "2009",
    doi: "",
    abstract: "This study is to develop and verify the reference model of the intelligent construction supply chain management process in order to provide the guide that can be easily applied when the process that reflects the numerous materials used for construction projects with such the factors is defined, through analyzing the feature of construction industry which considers the intelligent construction supply chain management and considering changing factors like the use of the intelligent equipment based on USN technology as a fundamental research for an efficient construction supply chain management system framework.",
    category: "그 외",
    keywords: "RFID , USN , 건설물류관리 , 프로세스 레퍼런스 모델 , 정보 모델"
  },
  {
    title: "IFC 를 중심으로 한 상용 3D CAD 의 호환성테스트",
    main_author: "임재인 ",
    co_authors: "김재우 , 권혁도 , 윤수원 , 권순욱 , 진상윤 ",
    journal: "한국건설관리학회",
    year: "2008",
    doi: "",
    abstract: "본 연구의 목적은 3D CAD Model을 이용하여 국제 건설데이터 교환표준인 IFC의 호환성을 테스트하고, IFC를 이용한 호환성 확보의 문제점을 도출하고자 한다.",
    category: "그 외",
    keywords: "IFC , IFC Viewer , BIM , 호환성테스트 , 3D CAD , IFC Viewer , Product Model Server"
  },
  {
    title: "RFID 기술적용 가능성 평가를 위한 각 공종별 주요자재 특성분석",
    main_author: "구도형 ",
    co_authors: "윤수원 , 진상윤 , 김예상 , 권순욱 ",
    journal: "한국건설관리학회",
    year: "2008",
    doi: "",
    abstract: "본 연구는 전체 건축프로젝트의 물류 및 진도관리를 위한 포괄적인 건설 물류 및 진도관리 통합체계를 개발하기 위한 기초 연구로서 각 공정별 주요자재에 RFID 기술을 적용하기 위해 공정 및 자재의 특성분석을 수행하였다.",
    category: "그 외",
    keywords: "건설물류 및 진도관리 , 가능성 및 한계"
  },
  {
    title: "커튼월 관련 자재에서 RFID 적용을 위한 인식 성능 테스트",
    main_author: "김용배 ",
    co_authors: "송제홍 , 윤수원 , 진상윤 , 권순욱 , 김예상 ",
    journal: "한국건설관리학회",
    year: "2008",
    doi: "",
    abstract: "본 연구에서는 위와 같은 테스트를 통해 커튼월에 RFID 기술 적용 시 인식 성능을 최적화하기 위한 고려 요소를 제시하고자 한다.",
    category: "그 외",
    keywords: "RFID , 커튼월 , 알루미늄 , 유리 , 인식성능"
  },
  {
    title: "Reading Performance Test of RFID Technology for Curtain Wall Material",
    main_author: "김용배 ",
    co_authors: "진상윤 , 권순욱 , 김예상 , 송제홍 , 윤수원 ",
    journal: "한국건설관리학회",
    year: "2008",
    doi: "",
    abstract: "본 연구에서는 위와 같은 테스트를 통해 커튼월에 RFID 기술 적용 시 인식 성능을 최적화하기 위한 고려 요소를 제시하고자 한다.",
    category: "그 외",
    keywords: "RFID , 커튼월 , 알루미늄 , 유리 , 인식성능"
  },
  {
    title: "An Analysis on the Characteristics of Work Items for RFID Technology Application Possibility Valuation",
    main_author: "구도형 ",
    co_authors: "윤수원 , 진상윤 , 김예상 , 권순욱 ",
    journal: "한국건설관리학회",
    year: "2008",
    doi: "",
    abstract: "This paper will make foundation of integrated framework for logistics and progress management in construction project, utilizing RFID technology by analysing materials type like materials which can be chased and measured, materials which can be chased and measured by certain methodologies, materials which can be chased and measured by future technologies, materials which are difficult to be chased and measured.",
    category: "그 외",
    keywords: "Logistics , Progress , RFID , Possibility , Limitations"
  },
  {
    title: "LIFTING LOAD RECORDING AND MANAGEMENT METHOD OF THE LIFT FOR CONSTRUCTION BASED SENSING INFORMATION",
    main_author: "고태규 ",
    co_authors: "이규협 , 권순욱 , 조청석 , 정수완 , 최고은",
    journal: "International Journal of High-Rise Buildings",
    year: "2022",
    doi: "doi.org/10.21022/IJHRB.2022.11.2.125",
    abstract: "This study presents a real-time lifting performance monitoring system that can store and manage lifting records for construction management.",
    category: "그 외",
    keywords: "Construction Lift , Lifting Record , Lifting Performance , Object Recognition Technique , Monitoring Of Lifting , Building Automation"
  },
  {
    title: "Smart home technologies supporting aging in place",
    main_author: "",
    co_authors: "",
    journal: "Gerontechnology",
    year: "2016",
    doi: "",
    abstract: "",
    category: "그 외",
    keywords: ""
  },
  {
    title: "A modified-AHP method of productivity analysis for deployment of innovative construction tools on construction site",
    main_author: "권순욱 ",
    co_authors: "이개영 , 안두영 , 박희성 ",
    journal: "Journal of Construction Engineering and Project Management",
    year: "2014",
    doi: "doi.org/10.6106/JCEPM.2014.4.1.045",
    abstract: "In this study, it is scraped up an application plan and selection for innovative tools by analyzing survey results on tool users and site managers with respect to using Modified-AHP performance measurement method.",
    category: "그 외",
    keywords: "Innovative tool , Productivity , AHP , Construction site operation"
  },
  {
    title: "BIM 도입의 국제 동향",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "건축",
    year: "2010",
    doi: "",
    abstract: "",
    category: "",
    keywords: ""
  },
  {
    title: "시공 및 CM 측면에서 바라본 Green Construction",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "건축",
    year: "2010",
    doi: "",
    abstract: "",
    category: "",
    keywords: ""
  },
  {
    title: "레이저 스캐닝 기술과 BIM 기술을 이용한 형상정보 획득기술의 건설산업 적용",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "건축",
    year: "2009",
    doi: "",
    abstract: "",
    category: "",
    keywords: ""
  },
  {
    title: "정보화 기반의 사회에서의 효율적인 건설 프로젝트 수행을 위한 자재 분류 및 관리방안",
    main_author: "권순욱 ",
    co_authors: "",
    journal: "건축과사회",
    year: "2009",
    doi: "",
    abstract: "",
    category: "",
    keywords: ""
  },
 ];
